# Generated by Django 6.0.2 on 2026-03-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('rent_price', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('vehicle_image', models.ImageField(upload_to='vehicles/')),
            ],
        ),
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.ImageField(upload_to='media/drivers/'),
        ),
    ]
