# Generated by Django 6.0.3 on 2026-03-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_vehicle_alter_driver_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='vehicle_types',
            field=models.TextField(null=True),
        ),
    ]
