# Generated by Django 6.0.3 on 2026-03-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_driver_vehicle_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('2W', 'Two Wheeler'), ('3W', 'Three Wheeler'), ('4W', 'Four Wheeler'), ('HV', 'Heavy Vehicle')], max_length=10, null=True),
        ),
    ]
