# Generated by Django 6.0.3 on 2026-03-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('vehicle_name', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(choices=[('2W', 'Two Wheeler'), ('3W', 'Three Wheeler'), ('4W', 'Four Wheeler'), ('HV', 'Heavy Vehicle')], max_length=2)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('num_days', models.PositiveIntegerField(default=1)),
                ('driver_needed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
