# Generated by Django 6.0.3 on 2026-03-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_vehiclebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclebooking',
            name='admin_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclebooking',
            name='driver_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
