# Generated by Django 6.0.3 on 2026-03-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_vehiclebooking_admin_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclebooking',
            name='lowest_driver_bid',
            field=models.IntegerField(null=True),
        ),
    ]
