# Generated by Django 6.0.3 on 2026-03-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_vehiclebooking_lowest_driver_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclebooking',
            name='accepted_driver_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
