# Generated by Django 6.0.3 on 2026-03-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_vehiclebooking_accepted_driver_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclebooking',
            name='accepted_driver_email',
        ),
        migrations.RemoveField(
            model_name='vehiclebooking',
            name='lowest_driver_bid',
        ),
    ]
