# Generated by Django 6.0.3 on 2026-03-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_remove_vehiclebooking_accepted_driver_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclebooking',
            name='admin_accepted',
        ),
        migrations.AddField(
            model_name='vehiclebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
