# Generated by Django 6.0.3 on 2026-03-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0013_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehichle_name', models.CharField(max_length=2)),
                ('requester_email', models.EmailField(max_length=254)),
                ('bidder', models.EmailField(max_length=254)),
                ('bid_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DriverRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_email', models.EmailField(max_length=254)),
                ('vehicle_type', models.CharField(choices=[('2W', 'Two Wheeler'), ('3W', 'Three Wheeler'), ('4W', 'Four Wheeler'), ('HV', 'Heavy Vehicle')], max_length=2)),
                ('lowest_bid', models.IntegerField()),
                ('lowest_bidder_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
