# Generated by Django 6.0.3 on 2026-03-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0014_bids_driverrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverrequests',
            name='vehichle_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bids',
            name='vehichle_name',
            field=models.CharField(max_length=50),
        ),
    ]
