# Generated by Django 6.0.3 on 2026-03-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0015_driverrequests_vehichle_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverrequests',
            old_name='vehichle_name',
            new_name='vehicle_name',
        ),
    ]
