# Generated by Django 6.0.3 on 2026-03-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0016_rename_vehichle_name_driverrequests_vehicle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverrequests',
            name='lowest_bid',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='driverrequests',
            name='lowest_bidder_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
