# Generated by Django 6.0.3 on 2026-03-24 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0017_alter_driverrequests_lowest_bid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='vehichle_name',
            new_name='vehicle_name',
        ),
    ]
