# Generated by Django 6.0.3 on 2026-03-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0018_rename_vehichle_name_bids_vehicle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverrequests',
            name='user_accepted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
